Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/04/2023
Var
// Seção de Declarações das variáveis 


Inicio

para i de 1 ate 10 faca
escreval("informe um numero")
leia (numero)
soma <- soma + numero
fimpara
escreval("o valor e!" , soma)


Fimalgoritmo