Algoritmo "teste04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2023
Var

valor :real
inicio
escreval("digite um valor")
leia(valor)
se (valor >10 ) entao
    escreval(" maior que  10:")

senao

    escreval("menor que 10:")
fimse






Fimalgoritmo